sudo: false

language: none

env:
  global:
    - COMPOSER_ARGS="--no-interaction"
    - ADAPTER_DEPS="alcaeus/mongo-php-adapter"
    - COVERAGE_DEPS="php-coveralls/php-coveralls"
    - MONGO_DRIVER=mongodb

matrix:
  include:
    - env:
        - TRAVIS_PHP_VERSION=5.6
        - DEPS=lowest
        - MONGO_DRIVER=mongo
    - env:
        - TRAVIS_PHP_VERSION=5.6
        - DEPS=locked
        - LEGACY_DEPS="doctrine/doctrine-module doctrine/doctrine-orm-module phpunit/phpunit zendframework/zend-code"
        - MONGO_DRIVER=mongo
    - env:
        - TRAVIS_PHP_VERSION=5.6
        - DEPS=latest
        - MONGO_DRIVER=mongo

before_install:
  - if [[ $TEST_COVERAGE != 'true' ]]; then phpenv config-rm xdebug.ini || return 0 ; fi

install:
  - yes '' | pecl -q install -f $MONGO_DRIVER
  - composer config platform.ext-mongo '1.999'
  - travis_retry composer install $COMPOSER_ARGS --ignore-platform-reqs
  - if [[ $LEGACY_DEPS != '' ]]; then travis_retry composer update $COMPOSER_ARGS --with-dependencies $LEGACY_DEPS ; fi
  - if [[ $DEPS == 'latest' ]]; then travis_retry composer update $COMPOSER_ARGS ; fi
  - if [[ $DEPS == 'lowest' ]]; then travis_retry composer update --prefer-lowest --prefer-stable $COMPOSER_ARGS ; fi
  - if [[ $MONGO_DRIVER == 'mongodb' ]]; then travis_retry composer require --dev $COMPOSER_ARGS $ADAPTER_DEPS ; fi
  - if [[ $TEST_COVERAGE == 'true' ]]; then travis_retry composer require --dev $COMPOSER_ARGS $COVERAGE_DEPS ; fi
  - stty cols 120 && composer show

script:
  - if [[ $TEST_COVERAGE == 'asdf' ]]; then composer test-coverage ; else composer test ; fi
  - if [[ $CS_CHECK == 'true' ]]; then composer cs-check ; fi
  - docker-compose run --rm php

after_script:
  - if [[ $TEST_COVERAGE == 'asdf' ]]; then travis_retry php vendor/bin/php-coveralls -v ; fi
