sudo: false
language: none

env:
  global:
    - COMPOSER_ARGS="--no-interaction"
    - ADAPTER_DEPS="alcaeus/mongo-php-adapter"
    - COVERAGE_DEPS="php-coveralls/php-coveralls"
    - MONGO_DRIVER="mongodb"

matrix:
  include:
    - env:
        - PHP_VERSION=5.6
        - DEPS=lowest
        - MONGO_DRIVER="mongo"
    - env:
        - PHP_VERSION=5.6
        - DEPS=locked
        - LEGACY_DEPS="doctrine/doctrine-module doctrine/doctrine-orm-module phpunit/phpunit zendframework/zend-code"
        - MONGO_DRIVER="mongo"
    - env:
        - PHP_VERSION=5.6
        - DEPS=latest
        - MONGO_DRIVER="mongo"
    - env:
        - PHP_VERSION=7
        - DEPS=lowest
    - env:
        - PHP_VERSION=7
        - DEPS=locked
        - LEGACY_DEPS="doctrine/doctrine-module doctrine/doctrine-orm-module phpunit/phpunit zendframework/zend-code"
    - env:
        - PHP_VERSION=7
        - DEPS=latest
    - env:
        - PHP_VERSION=7.1
        - DEPS=lowest
    - env:
        - PHP_VERSION=7.1
        - DEPS=locked
        - CS_CHECK=true
        - TEST_COVERAGE=true
        - XDEBUG=1
    - env:
        - PHP_VERSION=7.1
        - DEPS=latest
    - env:
        - PHP_VERSION=7.2
        - DEPS=lowest
    - env:
        - PHP_VERSION=7.2
        - DEPS=locked
    - env:
        - PHP_VERSION=7.2
        - DEPS=latest

before_install:
  - if [[ $TEST_COVERAGE != 'true' ]]; then phpenv config-rm xdebug.ini || return 0 ; fi

install:
  - docker-compose build --no-cache php
  - travis_retry docker-compose run --rm php composer install $COMPOSER_ARGS --ignore-platform-reqs

  - composer config "platform.ext-mongo" "1.6.16"
  - if [[ $LEGACY_DEPS != '' ]]; then travis_retry docker-compose run --rm php composer update $COMPOSER_ARGS --with-dependencies $LEGACY_DEPS ; fi
  - if [[ $DEPS == 'latest' ]]; then travis_retry docker-compose run --rm php composer update $COMPOSER_ARGS ; fi
  - if [[ $DEPS == 'lowest' ]]; then travis_retry docker-compose run --rm php composer update --prefer-lowest --prefer-stable $COMPOSER_ARGS ; fi
  - if [[ $MONGO_DRIVER == 'mongodb' ]] ; then travis_retry docker-compose run --rm php composer config "platform.ext-mongo" "1.6.16" && travis_retry docker-compose run --rm php composer require --dev $COMPOSER_ARGS $ADAPTER_DEPS ; fi
  - if [[ $TEST_COVERAGE == 'true' ]]; then travis_retry docker-compose run --rm php composer require --dev $COMPOSER_ARGS $COVERAGE_DEPS ; fi
  - stty cols 120 && composer show

script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then travis_retry docker-compose run --rm php composer test-coverage ; else docker-compose run --rm php composer test ; fi
  - if [[ $CS_CHECK == 'true' ]]; then travis_retry docker-compose run --rm php composer cs-check ; fi

after_script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then travis_retry docker-compose run --rm php vendor/bin/php-coveralls -v ; fi
