version: "3"
services:
  php:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION:-7.2}
        - XDEBUG=${XDEBUG:-0}
    depends_on:
      - mongo
    volumes:
      - ./:/docker
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017

  mongo:
    image: mongo:latest
