version: "3"
services:
  php:
    build:
      context: .
      dockerfile: docker/Dockerfile
    links:
      - mongo
    ports:
      - "9000:9000"
    volumes:
      - ./:/docker
    tty: true
  mongo:
    image: mongo:latest
